### ISSUE TITLE
AssertionError: would build wheel with unsupported tag ('cp38', 'cp39', 'linux_x86_64')

### ISSUE THREAD

**Issue by danli349** [slowkow/pytabix#11]
Hello:

I installed `pytabix` using `pip install --user pytabix`,
```
(base) dan@DESKTOP-0TJ97T7:~$ python -m pip install pytabix
Collecting pytabix
  Using cached pytabix-0.1.tar.gz (45 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pytabix
  Building wheel for pytabix (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [150 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/test
      copying test/test.py -> build/lib.linux-x86_64-cpython-38/test
      copying test/__init__.py -> build/lib.linux-x86_64-cpython-38/test
      copying test/example.gtf.gz -> build/lib.linux-x86_64-cpython-38/test
      copying test/example.gtf.gz.tbi -> build/lib.linux-x86_64-cpython-38/test
      running build_ext
      building 'tabix' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/src
      /home/dan/miniconda3/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dan/miniconda3/include -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE=1 -Isrc -I/home/dan/miniconda3/envs/r-reticulate/include/python3.9 -c src/bgzf.c -o build/temp.linux-x86_64-cpython-38/src/bgzf.o
      src/bgzf.c: In function 'bgzf_flush':
      src/bgzf.c:398:61: warning: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
        398 |   if (fwrite(fp->compressed_block, 1, block_length, fp->fp) != block_length) {
            |                                                             ^~
      src/bgzf.c: In function 'bgzf_close':
      src/bgzf.c:435:11: warning: variable 'count' set but not used [-Wunused-but-set-variable]
        435 |  int ret, count, block_length;
            |           ^~~~~
      /home/dan/miniconda3/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dan/miniconda3/include -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE=1 -Isrc -I/home/dan/miniconda3/envs/r-reticulate/include/python3.9 -c src/bgzip.c -o build/temp.linux-x86_64-cpython-38/src/bgzip.o
      /home/dan/miniconda3/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dan/miniconda3/include -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE=1 -Isrc -I/home/dan/miniconda3/envs/r-reticulate/include/python3.9 -c src/index.c -o build/temp.linux-x86_64-cpython-38/src/index.o
      In file included from src/index.c:5:
      src/index.c: In function 'ks_sample_offt':
      src/ksort.h:276:19: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
        276 |             if (k != n - pop - 1) tmp = a[k], a[k] = a[n-pop-1], a[n-pop-1] = tmp; \
            |                   ^~
      src/index.c:22:1: note: in expansion of macro 'KSORT_INIT'
         22 | KSORT_INIT(offt, pair64_t, pair64_lt)
            | ^~~~~~~~~~
      src/index.c: In function 'merge_chunks':
      src/index.c:267:18: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        267 |    for (l = 1; l < p->n; ++l) {
            |                  ^
      src/index.c: In function 'ti_index_core':
      src/index.c:310:14: warning: comparison of integer expressions of different signedness: 'uint64_t' {aka 'long unsigned int'} and 'int32_t' {aka 'int'} [-Wsign-compare]
        310 |   if (lineno <= idx->conf.line_skip || str->s[0] == idx->conf.meta_char) {
            |              ^~
      src/index.c:334:16: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        334 |   if (intv.bin != last_bin) { // then possibly write the binning index
            |                ^~
      src/index.c:342:21: warning: comparison of integer expressions of different signedness: 'int64_t' {aka 'long int'} and 'uint64_t' {aka 'long unsigned int'} [-Wsign-compare]
        342 |   if (bgzf_tell(fp) <= last_off) {
            |                     ^~
      src/index.c: In function 'ti_index_save':
      src/index.c:417:17: warning: comparison of integer expressions of different signedness: 'int32_t' {aka 'int'} and 'khint_t' {aka 'unsigned int'} [-Wsign-compare]
        417 |   for (i = 0; i < kh_size(idx->tname); ++i)
            |                 ^
      src/index.c:421:17: warning: comparison of integer expressions of different signedness: 'int32_t' {aka 'int'} and 'khint_t' {aka 'unsigned int'} [-Wsign-compare]
        421 |   for (i = 0; i < kh_size(idx->tname); ++i)
            |                 ^
      src/index.c:441:25: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        441 |      for (x = 0; (int)x < p->n; ++x) {
            |                         ^
      src/index.c:446:25: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        446 |      for (x = 0; (int)x < p->n; ++x) {
            |                         ^
      src/index.c: In function 'ti_index_load_core':
      src/index.c:546:19: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        546 |     for (x = 0; x < p->n; ++x) {
            |                   ^
      src/index.c: In function 'reg2bins':
      src/index.c:750:31: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        750 |  for (k =    1 + (beg>>26); k <=    1 + (end>>26); ++k) list[i++] = k;
            |                               ^~
      src/index.c:751:31: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        751 |  for (k =    9 + (beg>>23); k <=    9 + (end>>23); ++k) list[i++] = k;
            |                               ^~
      src/index.c:752:31: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        752 |  for (k =   73 + (beg>>20); k <=   73 + (end>>20); ++k) list[i++] = k;
            |                               ^~
      src/index.c:753:31: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        753 |  for (k =  585 + (beg>>17); k <=  585 + (end>>17); ++k) list[i++] = k;
            |                               ^~
      src/index.c:754:31: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        754 |  for (k = 4681 + (beg>>14); k <= 4681 + (end>>14); ++k) list[i++] = k;
            |                               ^~
      src/index.c: In function 'ti_iter_query':
      src/index.c:808:18: warning: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
        808 |    for (j = 0; j < p->n; ++j)
            |                  ^
      /home/dan/miniconda3/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dan/miniconda3/include -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE=1 -Isrc -I/home/dan/miniconda3/envs/r-reticulate/include/python3.9 -c src/knetfile.c -o build/temp.linux-x86_64-cpython-38/src/knetfile.o
      /home/dan/miniconda3/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dan/miniconda3/include -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE=1 -Isrc -I/home/dan/miniconda3/envs/r-reticulate/include/python3.9 -c src/kstring.c -o build/temp.linux-x86_64-cpython-38/src/kstring.o
      src/kstring.c: In function 'ksprintf':
      src/kstring.c:15:12: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
         15 |  if (l + 1 > s->m - s->l) {
            |            ^
      /home/dan/miniconda3/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/envs/r-reticulate/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dan/miniconda3/include -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE=1 -Isrc -I/home/dan/miniconda3/envs/r-reticulate/include/python3.9 -c src/tabixmodule.c -o build/temp.linux-x86_64-cpython-38/src/tabixmodule.o
      /home/dan/miniconda3/bin/x86_64-conda-linux-gnu-cc -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/dan/miniconda3/envs/r-reticulate/lib -Wl,-rpath-link,/home/dan/miniconda3/envs/r-reticulate/lib -L/home/dan/miniconda3/envs/r-reticulate/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/dan/miniconda3/envs/r-reticulate/lib -Wl,-rpath-link,/home/dan/miniconda3/envs/r-reticulate/lib -L/home/dan/miniconda3/envs/r-reticulate/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/dan/miniconda3/lib -Wl,-rpath-link,/home/dan/miniconda3/lib -L/home/dan/miniconda3/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dan/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dan/miniconda3/include build/temp.linux-x86_64-cpython-38/src/bgzf.o build/temp.linux-x86_64-cpython-38/src/bgzip.o build/temp.linux-x86_64-cpython-38/src/index.o build/temp.linux-x86_64-cpython-38/src/knetfile.o build/temp.linux-x86_64-cpython-38/src/kstring.o build/temp.linux-x86_64-cpython-38/src/tabixmodule.o -lz -o build/lib.linux-x86_64-cpython-38/tabix.cpython-39-x86_64-linux-gnu.so
      /home/dan/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer, pypa/build or
              other standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      creating build/bdist.linux-x86_64
      creating build/bdist.linux-x86_64/wheel
      copying build/lib.linux-x86_64-cpython-38/tabix.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
      creating build/bdist.linux-x86_64/wheel/test
      copying build/lib.linux-x86_64-cpython-38/test/example.gtf.gz -> build/bdist.linux-x86_64/wheel/test
      copying build/lib.linux-x86_64-cpython-38/test/example.gtf.gz.tbi -> build/bdist.linux-x86_64/wheel/test
      copying build/lib.linux-x86_64-cpython-38/test/test.py -> build/bdist.linux-x86_64/wheel/test
      copying build/lib.linux-x86_64-cpython-38/test/__init__.py -> build/bdist.linux-x86_64/wheel/test
      running install_egg_info
      running egg_info
      writing pytabix.egg-info/PKG-INFO
      writing dependency_links to pytabix.egg-info/dependency_links.txt
      writing top-level names to pytabix.egg-info/top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'pytabix.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'pytabix.egg-info/SOURCES.txt'
      Copying pytabix.egg-info to build/bdist.linux-x86_64/wheel/pytabix-0.1-py3.8.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d5j3v7t8/pytabix_0661ab4e80634320b547818359ec62d5/setup.py", line 45, in <module>
          setup(
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/dan/miniconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 380, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/home/dan/miniconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 329, in get_tag
          assert (
      AssertionError: would build wheel with unsupported tag ('cp38', 'cp39', 'linux_x86_64')
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytabix
  Running setup.py clean for pytabix
Failed to build pytabix
ERROR: Could not build wheels for pytabix, which is required to install pyproject.toml-based projects
```

but in `python` I can't import it:

```
(base) dan@DESKTOP-0TJ97T7:~$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tabix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tabix'
```
How can I fix it?
Thanks

**Comment by slowkow** [comment]
The README says we should write `import tabix`, not `import pytabix`.

**Comment by danli349** [comment]
> The README says we should write `import tabix`, not `import pytabix`.

@slowkow I am sorry there is an error during installing `pytabix`, I modified the question.
Can you please let me know how to fix it? Thanks a lot.

**Comment by slowkow** [comment]
Right now on my server I successfully ran `pip install pytabix` with no surprises, and the code example in the README still works as expected.

This indicates that the problem is likely to be in your configuration, not in the pytabix code. But I could be mistaken, and I'm not certain what is causing your error.

Here is your error:

```
AssertionError: would build wheel with unsupported tag ('cp38', 'cp39', 'linux_x86_64')
```

Here's one result I found from Google:

https://stackoverflow.com/questions/64611957/assertionerror-would-build-wheel-with-unsupported-tag-cp310-cp310-linux

I expect that the issue has to do with your python version, or with your compilers. Good luck!

**Comment by danli349** [comment]
@slowkow I work around to successfully install `pytabix` by `conda`

```
(base) dan@DESKTOP-0TJ97T7:~$ conda install -c bioconda pytabix
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.11.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0



## Package Plan ##

  environment location: /home/dan/miniconda3

  added / updated specs:
    - pytabix


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytabix-0.1                |   py38h8e3bb3f_1          50 KB  bioconda
    ------------------------------------------------------------
                                           Total:          50 KB

The following NEW packages will be INSTALLED:

  pytabix            bioconda/linux-64::pytabix-0.1-py38h8e3bb3f_1


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

```
(base) dan@DESKTOP-0TJ97T7:~$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tabix
>>>

```

**Comment by slowkow** [comment]
Great, thanks for sharing your solution.
